import { create } from 'zustand';

export type Language = 'pt' | 'es' | 'en';

interface LanguageStore {
  language: Language;
  setLanguage: (lang: Language) => void;
}

export const useLanguageStore = create<LanguageStore>((set) => ({
  language: 'pt',
  setLanguage: (language) => set({ language }),
}));

// ─── TRANSLATIONS ─────────────────────────────────────────────────────────────

export const T = {
  pt: {
    // Home
    appName: 'Story Shot',
    tagline: 'O party game que te amaldiçoa',
    classicMode: 'Modo Clássico',
    classicDesc: 'Cenas aleatórias, caos puro, maldições imprevisíveis',
    storyMode: 'Modo História',
    storyDesc: 'Você escolhe o lugar, a IA cria a história com sarcasmo',
    howToPlay: 'Como jogar?',
    costs: '💰 Gastos da IA',
    // Players
    players: 'Jogadores',
    playersSubtitle: 'Adicione de 2 a 12 jogadores',
    playerPlaceholder: 'Jogador',
    addPlayer: '+ Adicionar jogador',
    minPlayers: '(mínimo 2)',
    next: 'Próximo →',
    back: 'Voltar',
    // Story Setup
    storyTitle: 'Modo História',
    storySubtitle: 'A IA cria uma história no lugar que você escolher',
    whereLabel: 'Onde a história acontece?',
    wherePlaceholder: 'Ex: bar de faculdade, castelo assombrado, metrô...',
    whereHint: 'Quanto mais específico, mais engraçado fica',
    intensityLabel: 'Intensidade',
    roundsLabel: 'Quantidade de rounds (máx 8)',
    estimatedTime: 'min estimados',
    startStory: 'Começar a história 📖',
    creating: 'Criando o lugar...',
    // Intensity
    leve: 'Leve', leveDesc: 'Sarcasmo suave',
    media: 'Média', mediaDesc: 'Caos moderado',
    pesada: 'Pesada', pesadaDesc: 'Sem piedade',
    // Game
    round: 'Rodada',
    turn: 'Turno',
    groupEvent: '🔥 EVENTO COLETIVO',
    groupEventDesc: 'Todos estão envolvidos',
    groupDecides: 'Grupo decide — vez de',
    yourTurn: 'Vez de',
    whatGroupDoes: 'O que o grupo faz?',
    whatYouDo: 'O que você faz?',
    storyLoading: 'A história continua...',
    destinyLoading: 'A história decide o destino...',
    // Result
    chose: 'escolheu:',
    nextRound: 'Continuar a história →',
    finalRound: 'Ver final da história 🏆',
    // Finale
    endOfStory: 'Fim da História',
    roundsOfChaos: 'rodadas de caos puro',
    epilogueLoading: 'Escrevendo o epílogo...',
    finalScore: '📊 Placar final',
    playAgain: 'Jogar novamente 🎲',
    // Wake backend
    wakeBackend: '⚡ Ligar servidor',
    waking: 'Ligando...',
    wakeOk: '✅ Servidor online',
    wakeFail: '❌ Falhou, tente novamente',
    // How to play
    howToPlayTitle: 'Como Jogar',
    understood: 'Entendi, vamos jogar',
    // Rules
    activeRules: 'regra ativa',
    activeRulesPlural: 'regras ativas',
    // Drinks
    whodrinks: '🍺 Quem bebe',
    nodrink: '✨ Ninguém bebe dessa vez!',
    sip: 'gole',
    sips: 'goles',
    newRule: '📜 Nova regra',
    forRounds: 'por',
    untilEnd: 'até o fim do jogo',
    roundSingular: 'rodada',
    roundPlural: 'rodadas',
  },
  es: {
    appName: 'Story Shot',
    tagline: 'El party game que te maldice',
    classicMode: 'Modo Clásico',
    classicDesc: 'Escenas aleatorias, caos puro, maldiciones impredecibles',
    storyMode: 'Modo Historia',
    storyDesc: 'Tú eliges el lugar, la IA crea la historia con sarcasmo',
    howToPlay: '¿Cómo jugar?',
    costs: '💰 Gastos de IA',
    players: 'Jugadores',
    playersSubtitle: 'Agrega de 2 a 12 jugadores',
    playerPlaceholder: 'Jugador',
    addPlayer: '+ Agregar jugador',
    minPlayers: '(mínimo 2)',
    next: 'Siguiente →',
    back: 'Volver',
    storyTitle: 'Modo Historia',
    storySubtitle: 'La IA crea una historia en el lugar que elijas',
    whereLabel: '¿Dónde ocurre la historia?',
    wherePlaceholder: 'Ej: bar universitario, castillo embrujado, metro...',
    whereHint: 'Cuanto más específico, más gracioso queda',
    intensityLabel: 'Intensidad',
    roundsLabel: 'Cantidad de rondas (máx 8)',
    estimatedTime: 'min estimados',
    startStory: 'Comenzar historia 📖',
    creating: 'Creando el lugar...',
    leve: 'Suave', leveDesc: 'Sarcasmo leve',
    media: 'Media', mediaDesc: 'Caos moderado',
    pesada: 'Pesada', pesadaDesc: 'Sin piedad',
    round: 'Ronda',
    turn: 'Turno',
    groupEvent: '🔥 EVENTO COLECTIVO',
    groupEventDesc: 'Todos están involucrados',
    groupDecides: 'Grupo decide — turno de',
    yourTurn: 'Turno de',
    whatGroupDoes: '¿Qué hace el grupo?',
    whatYouDo: '¿Qué haces?',
    storyLoading: 'La historia continúa...',
    destinyLoading: 'La historia decide tu destino...',
    chose: 'eligió:',
    nextRound: 'Continuar historia →',
    finalRound: 'Ver final de la historia 🏆',
    endOfStory: 'Fin de la Historia',
    roundsOfChaos: 'rondas de caos puro',
    epilogueLoading: 'Escribiendo el epílogo...',
    finalScore: '📊 Puntuación final',
    playAgain: 'Jugar de nuevo 🎲',
    wakeBackend: '⚡ Encender servidor',
    waking: 'Encendiendo...',
    wakeOk: '✅ Servidor online',
    wakeFail: '❌ Falló, intenta de nuevo',
    howToPlayTitle: 'Cómo Jugar',
    understood: 'Entendido, vamos a jugar',
    activeRules: 'regla activa',
    activeRulesPlural: 'reglas activas',
    whodrinks: '🍺 Quién bebe',
    nodrink: '✨ ¡Nadie bebe esta vez!',
    sip: 'trago',
    sips: 'tragos',
    newRule: '📜 Nueva regla',
    forRounds: 'por',
    untilEnd: 'hasta el fin del juego',
    roundSingular: 'ronda',
    roundPlural: 'rondas',
  },
  en: {
    appName: 'Story Shot',
    tagline: 'The party game that curses you',
    classicMode: 'Classic Mode',
    classicDesc: 'Random scenes, pure chaos, unpredictable curses',
    storyMode: 'Story Mode',
    storyDesc: 'You pick the place, AI creates the story with sarcasm',
    howToPlay: 'How to play?',
    costs: '💰 AI Costs',
    players: 'Players',
    playersSubtitle: 'Add 2 to 12 players',
    playerPlaceholder: 'Player',
    addPlayer: '+ Add player',
    minPlayers: '(minimum 2)',
    next: 'Next →',
    back: 'Back',
    storyTitle: 'Story Mode',
    storySubtitle: 'AI creates a story in the place you choose',
    whereLabel: 'Where does the story take place?',
    wherePlaceholder: 'E.g.: college bar, haunted castle, subway...',
    whereHint: 'The more specific, the funnier it gets',
    intensityLabel: 'Intensity',
    roundsLabel: 'Number of rounds (max 8)',
    estimatedTime: 'min estimated',
    startStory: 'Start story 📖',
    creating: 'Creating the place...',
    leve: 'Light', leveDesc: 'Mild sarcasm',
    media: 'Medium', mediaDesc: 'Moderate chaos',
    pesada: 'Heavy', pesadaDesc: 'No mercy',
    round: 'Round',
    turn: 'Turn',
    groupEvent: '🔥 GROUP EVENT',
    groupEventDesc: 'Everyone is involved',
    groupDecides: 'Group decides — turn of',
    yourTurn: 'Turn of',
    whatGroupDoes: 'What does the group do?',
    whatYouDo: 'What do you do?',
    storyLoading: 'The story continues...',
    destinyLoading: 'The story decides your fate...',
    chose: 'chose:',
    nextRound: 'Continue story →',
    finalRound: 'See story ending 🏆',
    endOfStory: 'End of Story',
    roundsOfChaos: 'rounds of pure chaos',
    epilogueLoading: 'Writing the epilogue...',
    finalScore: '📊 Final score',
    playAgain: 'Play again 🎲',
    wakeBackend: '⚡ Wake server',
    waking: 'Waking up...',
    wakeOk: '✅ Server online',
    wakeFail: '❌ Failed, try again',
    howToPlayTitle: 'How to Play',
    understood: 'Got it, let\'s play',
    activeRules: 'active rule',
    activeRulesPlural: 'active rules',
    whodrinks: '🍺 Who drinks',
    nodrink: '✨ Nobody drinks this time!',
    sip: 'sip',
    sips: 'sips',
    newRule: '📜 New rule',
    forRounds: 'for',
    untilEnd: 'until end of game',
    roundSingular: 'round',
    roundPlural: 'rounds',
  },
} as const;

export type TranslationKey = keyof typeof T['pt'];

export function useT() {
  const language = useLanguageStore(s => s.language);
  return T[language];
}
