import { create } from 'zustand';

export type Language = 'pt' | 'es' | 'en';

interface LanguageStore {
  language: Language;
  setLanguage: (lang: Language) => void;
}

export const useLanguageStore = create<LanguageStore>((set) => ({
  language: 'pt',
  setLanguage: (language) => set({ language }),
}));

// â”€â”€â”€ TRANSLATIONS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export const T = {
  pt: {
    // Home
    appName: 'Story Shot',
    tagline: 'O party game que te amaldiÃ§oa',
    classicMode: 'Modo ClÃ¡ssico',
    classicDesc: 'Cenas aleatÃ³rias, caos puro, maldiÃ§Ãµes imprevisÃ­veis',
    storyMode: 'Modo HistÃ³ria',
    storyDesc: 'VocÃª escolhe o lugar, a IA cria a histÃ³ria com sarcasmo',
    howToPlay: 'Como jogar?',
    costs: 'ðŸ’° Gastos da IA',
    // Players
    players: 'Jogadores',
    playersSubtitle: 'Adicione de 2 a 12 jogadores',
    playerPlaceholder: 'Jogador',
    addPlayer: '+ Adicionar jogador',
    minPlayers: '(mÃ­nimo 2)',
    next: 'PrÃ³ximo â†’',
    back: 'Voltar',
    // Story Setup
    storyTitle: 'Modo HistÃ³ria',
    storySubtitle: 'A IA cria uma histÃ³ria no lugar que vocÃª escolher',
    whereLabel: 'Onde a histÃ³ria acontece?',
    wherePlaceholder: 'Ex: bar de faculdade, castelo assombrado, metrÃ´...',
    whereHint: 'Quanto mais especÃ­fico, mais engraÃ§ado fica',
    intensityLabel: 'Intensidade',
    roundsLabel: 'Quantidade de rounds (mÃ¡x 8)',
    estimatedTime: 'min estimados',
    startStory: 'ComeÃ§ar a histÃ³ria ðŸ“–',
    creating: 'Criando o lugar...',
    // Intensity
    leve: 'Leve', leveDesc: 'Sarcasmo suave',
    media: 'MÃ©dia', mediaDesc: 'Caos moderado',
    pesada: 'Pesada', pesadaDesc: 'Sem piedade',
    // Game
    round: 'Rodada',
    turn: 'Turno',
    groupEvent: 'ðŸ”¥ EVENTO COLETIVO',
    groupEventDesc: 'Todos estÃ£o envolvidos',
    groupDecides: 'Grupo decide â€” vez de',
    yourTurn: 'Vez de',
    whatGroupDoes: 'O que o grupo faz?',
    whatYouDo: 'O que vocÃª faz?',
    storyLoading: 'A histÃ³ria continua...',
    destinyLoading: 'A histÃ³ria decide o destino...',
    // Result
    chose: 'escolheu:',
    nextRound: 'Continuar a histÃ³ria â†’',
    finalRound: 'Ver final da histÃ³ria ðŸ†',
    // Finale
    endOfStory: 'Fim da HistÃ³ria',
    roundsOfChaos: 'rodadas de caos puro',
    epilogueLoading: 'Escrevendo o epÃ­logo...',
    finalScore: 'ðŸ“Š Placar final',
    playAgain: 'Jogar novamente ðŸŽ²',
    // Wake backend
    wakeBackend: 'âš¡ Ligar servidor',
    waking: 'Ligando...',
    wakeOk: 'âœ… Servidor online',
    wakeFail: 'âŒ Falhou, tente novamente',
    // How to play
    howToPlayTitle: 'Como Jogar',
    understood: 'Entendi, vamos jogar',
    // Rules
    activeRules: 'regra ativa',
    activeRulesPlural: 'regras ativas',
    // Drinks
    whodrinks: 'ðŸº Quem bebe',
    nodrink: 'âœ¨ NinguÃ©m bebe dessa vez!',
    sip: 'gole',
    sips: 'goles',
    newRule: 'ðŸ“œ Nova regra',
    forRounds: 'por',
    untilEnd: 'atÃ© o fim do jogo',
    roundSingular: 'rodada',
    roundPlural: 'rodadas',
  },
  es: {
    appName: 'Story Shot',
    tagline: 'El party game que te maldice',
    classicMode: 'Modo ClÃ¡sico',
    classicDesc: 'Escenas aleatorias, caos puro, maldiciones impredecibles',
    storyMode: 'Modo Historia',
    storyDesc: 'TÃº eliges el lugar, la IA crea la historia con sarcasmo',
    howToPlay: 'Â¿CÃ³mo jugar?',
    costs: 'ðŸ’° Gastos de IA',
    players: 'Jugadores',
    playersSubtitle: 'Agrega de 2 a 12 jugadores',
    playerPlaceholder: 'Jugador',
    addPlayer: '+ Agregar jugador',
    minPlayers: '(mÃ­nimo 2)',
    next: 'Siguiente â†’',
    back: 'Volver',
    storyTitle: 'Modo Historia',
    storySubtitle: 'La IA crea una historia en el lugar que elijas',
    whereLabel: 'Â¿DÃ³nde ocurre la historia?',
    wherePlaceholder: 'Ej: bar universitario, castillo embrujado, metro...',
    whereHint: 'Cuanto mÃ¡s especÃ­fico, mÃ¡s gracioso queda',
    intensityLabel: 'Intensidad',
    roundsLabel: 'Cantidad de rondas (mÃ¡x 8)',
    estimatedTime: 'min estimados',
    startStory: 'Comenzar historia ðŸ“–',
    creating: 'Creando el lugar...',
    leve: 'Suave', leveDesc: 'Sarcasmo leve',
    media: 'Media', mediaDesc: 'Caos moderado',
    pesada: 'Pesada', pesadaDesc: 'Sin piedad',
    round: 'Ronda',
    turn: 'Turno',
    groupEvent: 'ðŸ”¥ EVENTO COLECTIVO',
    groupEventDesc: 'Todos estÃ¡n involucrados',
    groupDecides: 'Grupo decide â€” turno de',
    yourTurn: 'Turno de',
    whatGroupDoes: 'Â¿QuÃ© hace el grupo?',
    whatYouDo: 'Â¿QuÃ© haces?',
    storyLoading: 'La historia continÃºa...',
    destinyLoading: 'La historia decide tu destino...',
    chose: 'eligiÃ³:',
    nextRound: 'Continuar historia â†’',
    finalRound: 'Ver final de la historia ðŸ†',
    endOfStory: 'Fin de la Historia',
    roundsOfChaos: 'rondas de caos puro',
    epilogueLoading: 'Escribiendo el epÃ­logo...',
    finalScore: 'ðŸ“Š PuntuaciÃ³n final',
    playAgain: 'Jugar de nuevo ðŸŽ²',
    wakeBackend: 'âš¡ Encender servidor',
    waking: 'Encendiendo...',
    wakeOk: 'âœ… Servidor online',
    wakeFail: 'âŒ FallÃ³, intenta de nuevo',
    howToPlayTitle: 'CÃ³mo Jugar',
    understood: 'Entendido, vamos a jugar',
    activeRules: 'regla activa',
    activeRulesPlural: 'reglas activas',
    whodrinks: 'ðŸº QuiÃ©n bebe',
    nodrink: 'âœ¨ Â¡Nadie bebe esta vez!',
    sip: 'trago',
    sips: 'tragos',
    newRule: 'ðŸ“œ Nueva regla',
    forRounds: 'por',
    untilEnd: 'hasta el fin del juego',
    roundSingular: 'ronda',
    roundPlural: 'rondas',
  },
  en: {
    appName: 'Story Shot',
    tagline: 'The party game that curses you',
    classicMode: 'Classic Mode',
    classicDesc: 'Random scenes, pure chaos, unpredictable curses',
    storyMode: 'Story Mode',
    storyDesc: 'You pick the place, AI creates the story with sarcasm',
    howToPlay: 'How to play?',
    costs: 'ðŸ’° AI Costs',
    players: 'Players',
    playersSubtitle: 'Add 2 to 12 players',
    playerPlaceholder: 'Player',
    addPlayer: '+ Add player',
    minPlayers: '(minimum 2)',
    next: 'Next â†’',
    back: 'Back',
    storyTitle: 'Story Mode',
    storySubtitle: 'AI creates a story in the place you choose',
    whereLabel: 'Where does the story take place?',
    wherePlaceholder: 'E.g.: college bar, haunted castle, subway...',
    whereHint: 'The more specific, the funnier it gets',
    intensityLabel: 'Intensity',
    roundsLabel: 'Number of rounds (max 8)',
    estimatedTime: 'min estimated',
    startStory: 'Start story ðŸ“–',
    creating: 'Creating the place...',
    leve: 'Light', leveDesc: 'Mild sarcasm',
    media: 'Medium', mediaDesc: 'Moderate chaos',
    pesada: 'Heavy', pesadaDesc: 'No mercy',
    round: 'Round',
    turn: 'Turn',
    groupEvent: 'ðŸ”¥ GROUP EVENT',
    groupEventDesc: 'Everyone is involved',
    groupDecides: 'Group decides â€” turn of',
    yourTurn: 'Turn of',
    whatGroupDoes: 'What does the group do?',
    whatYouDo: 'What do you do?',
    storyLoading: 'The story continues...',
    destinyLoading: 'The story decides your fate...',
    chose: 'chose:',
    nextRound: 'Continue story â†’',
    finalRound: 'See story ending ðŸ†',
    endOfStory: 'End of Story',
    roundsOfChaos: 'rounds of pure chaos',
    epilogueLoading: 'Writing the epilogue...',
    finalScore: 'ðŸ“Š Final score',
    playAgain: 'Play again ðŸŽ²',
    wakeBackend: 'âš¡ Wake server',
    waking: 'Waking up...',
    wakeOk: 'âœ… Server online',
    wakeFail: 'âŒ Failed, try again',
    howToPlayTitle: 'How to Play',
    understood: 'Got it, let\'s play',
    activeRules: 'active rule',
    activeRulesPlural: 'active rules',
    whodrinks: 'ðŸº Who drinks',
    nodrink: 'âœ¨ Nobody drinks this time!',
    sip: 'sip',
    sips: 'sips',
    newRule: 'ðŸ“œ New rule',
    forRounds: 'for',
    untilEnd: 'until end of game',
    roundSingular: 'round',
    roundPlural: 'rounds',
  },
} as const;

export type TranslationKey = keyof typeof T['pt'];

export function useT() {
  const language = useLanguageStore(s => s.language);
  return T[language];
}

